version: '3.8'

services:
  app:
    image: urlshortener/dockerdemofebruary:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/urlshortenerdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1235
    depends_on:
      - db
    command: [ "./wait-for-it.sh", "db:3306", "--timeout=60", "--", "java", "-jar", "dockerdemofebruary.jar" ]




  db:
    image: mysql:8.3.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1235
      MYSQL_DATABASE: urlshortenerdb
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - urlshortener_mysql_data:/var/lib/mysql

volumes:
  urlshortener_mysql_data:

