spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortenerdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1235
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MYSQL5Dialect
    hibernate:
      ddl-auto: update